# Ruta: alembic/versions/00000000_0000_0001_enable_pgvector.py
"""enable pgvector extension

This migration is intentionally hand-written and placed first in the chain.
`document_chunks.embedding` uses the `vector` type, which requires the
`pgvector` extension to exist BEFORE any table referencing it is created.
Autogenerate won't emit this, so it lives here as the base revision every
autogenerated migration builds on top of.

Revision ID: 0001_enable_pgvector
Revises:
Create Date: 2026-01-01 00:00:00
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0001_enable_pgvector"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")