"""add group_messages, deck_name, room exam fields

Revision ID: 86ce0c084d93
Revises: 4be0946a4612
Create Date: 2026-07-10 15:26:57.662711+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '86ce0c084d93'
down_revision: Union[str, None] = '4be0946a4612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['study_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_messages_room_id'), 'group_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_group_messages_user_id'), 'group_messages', ['user_id'], unique=False)

    # --- Exam.room_id: 1. agregar como nullable primero ---
    op.add_column('exams', sa.Column('room_id', sa.UUID(), nullable=True))

    # Postgres no crea el tipo ENUM solo cuando lo agregas vía ADD COLUMN
    # a una tabla existente (sí lo hace automáticamente en un CREATE TABLE
    # nuevo, como group_messages arriba) — hay que crearlo explícitamente
    # primero, o el ALTER TABLE de abajo falla con UndefinedObjectError.
    exam_status_enum = postgresql.ENUM(
        'PENDING', 'READY', 'FAILED', name='exam_generation_status_enum'
    )
    exam_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'exams',
        sa.Column('status', exam_status_enum, server_default='READY', nullable=False),
    )

    op.alter_column('exams', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)

    # --- 2. Backfill room_id desde el documento padre ---
    op.execute("""
        UPDATE exams
        SET room_id = documents.room_id
        FROM documents
        WHERE exams.document_id = documents.id
    """)

    # --- 3. Ahora sí, NOT NULL, índice y FK ---
    op.alter_column('exams', 'room_id', nullable=False)
    op.create_index(op.f('ix_exams_room_id'), 'exams', ['room_id'], unique=False)
    op.create_foreign_key(None, 'exams', 'study_rooms', ['room_id'], ['id'], ondelete='CASCADE')

    op.add_column('flashcards', sa.Column('deck_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_flashcards_deck_name'), 'flashcards', ['deck_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcards_deck_name'), table_name='flashcards')
    op.drop_column('flashcards', 'deck_name')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_index(op.f('ix_exams_room_id'), table_name='exams')
    op.alter_column('exams', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('exams', 'status')
    # El tipo ENUM también hay que borrarlo explícitamente al revertir —
    # dejarlo huérfano rompería un upgrade posterior (el tipo ya existiría).
    postgresql.ENUM(name='exam_generation_status_enum').drop(op.get_bind(), checkfirst=True)
    op.drop_column('exams', 'room_id')
    op.drop_index(op.f('ix_group_messages_user_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_room_id'), table_name='group_messages')
    op.drop_table('group_messages')
    # ### end Alembic commands ###