"""add join_code to study_rooms

Revision ID: 4be0946a4612
Revises: 0002_add_flashcards_fields
Create Date: 2026-07-10 05:10:03.279455+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4be0946a4612'
down_revision: Union[str, None] = '0002_add_flashcards_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_rooms', sa.Column('join_code', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_study_rooms_join_code'), 'study_rooms', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_rooms_join_code'), table_name='study_rooms')
    op.drop_column('study_rooms', 'join_code')
    # ### end Alembic commands ###
